[package]
name = "zipit"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.13", features = ["macros", "fs", "io-util", "rt-multi-thread"] }
crc32fast = "1.2"
chrono = { version = "0.4", optional = true }

[features]
chrono-datetime = ["chrono"]