[package]
name = "zipit"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.13", default-features = false, features = ["io-util"] }
crc32fast = "1.2"
chrono = { version = "0.4", optional = true }

[dev-dependencies]
tokio = { version = "1.13", features = ["macros", "rt-multi-thread"] }

[features]
chrono-datetime = ["chrono"]